SCR_MissionHeaderCampaign {
 World "{82B2DCDD17534134}lesovayaconflict.ent"
 m_sName "lesovaya Conflict (not working)"
 m_sAuthor "Plaindelta"
 m_sDescription "lesovaya Conflict (not working)"
 m_sIcon "{C02195B6F7B44353}Satmap/newsatmapnobuild.edds"
 m_sGameMode "#AR-Campaign_GamemodeName"
 m_iPlayerCount 128
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
}