SCR_MissionHeader {
 World "{299ECE8A9C02ADBC}lesoavyaGAMEMASTER.ent"
 m_sName "lesovaya Gamemaster"
 m_sAuthor "Plaindelta"
 m_sDescription "lesovaya work in progress build map"
 m_sIcon "{23C8062113F1B3E2}Pictures/12454.edds"
 m_sLoadingScreen "{23C8062113F1B3E2}Pictures/12454.edds"
 m_sPreviewImage "{07AE9170F4EDA740}Pictures/lespic.edds"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
 m_iStartingHours 11
 m_bIsArmavisionAllowedInMP 1
}